### PR TITLE
Add more linters to .golangci.yml

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Adds more linters to .golangci.yml and bumps go to 1.20 in GH workflow files

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by alexander-demicev** [comment]
@furkatgofurov7 1.20 fails linter, look like it's incompatible with golangci

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 1.20 fails linter, look like it's incompatible with golangci

yeah, I was hoping `cache: false` would help..

**Comment by alexander-demicev** [comment]
We have to wait until golangci updates to 1.20

**Comment by furkatgofurov7** [comment]
> We have to wait until golangci updates to 1.20

@alexander-demicev looks like I had to specify the patch version of v1.20 version series instead of just v1.20

**Review by alexander-demicev — APPROVED** [review]

**Review by Danil-Grigorev — APPROVED** [review]

**Pull request merged**
