### PR TITLE
Stop publishing nightly images to prime registry

### PR DESCRIPTION
**Pull request by alexander-demicev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
Q: why we need to stop?

**Comment by alexander-demicev** [comment]
@furkatgofurov7 To my understanding prime registry is only for ready and released images, not CI or testing. cc @richardcase

**Comment by salasberryfin** [comment]
LGTM. Not publishing to the prod registry is also what we agreed on when setting up the [nightly release test](https://github.com/rancher-sandbox/rancher-turtles/blob/main/.github/workflows/nightly-test-release.yaml)

**Review by salasberryfin — DISMISSED** [review]

**Review by richardcase — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
@alexander-demicev can we rebase, otherwise this LGTM

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
