### PR TITLE
🌱 Apply embedded capi feature flag after rancher install

### LINKED ISSUE #188: [E2E] Add a test that covers already existing Rancher Manager cluster
All our E2E tests currently assume we disable embedded CAPI from the install time of Rancher. However, a lot of customers will install Rancher Turtles in an already existing cluster.

This currently breaks RT.

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
kind/chore

**What this PR does / why we need it**:
This PR converts all existing gitops scenarios to a rancher installation with post-install step applying required feature gates as per documented [installation process](https://docs.rancher-turtles.com/docs/getting-started/rancher#installing-rancher).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #188 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Review by alexander-demicev — APPROVED** [review]

**Comment by Danil-Grigorev** [comment]
> will this fail e2e until webhooks are fixed in rancher?

Yes, until the implementation part is done the e2e tests would fail to apply CAPI cluster with this coming from fleet logs:
```
2023-10-04T12:02:42.442248697Z stderr F time="2023-10-04T12:02:42Z" level=error msg="error syncing 'cluster-fleet-local-local-1a3d67d0a899/repo-creategitops-eclnmh-clusters': handler bundle-deploy: failed to create resource: Internal error occurred: failed calling webhook \"default.cluster.cluster.x-k8s.io\": failed to call webhook: Post \"https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s\": service \"webhook-service\" not found, requeuing"
```

**Comment by richardcase** [comment]
Until we have that feature in Rancher turtles we can always use [RunCommand](https://github.com/rancher-sandbox/rancher-turtles/blob/main/test/framework/command_helper.go#L44) to run the following after disabling the feature and waiting for the Rancher CAPI deployment to be removed:

```bash
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io mutating-webhook-configuration
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io validating-webhook-configuration
```

**Comment by richardcase** [comment]
Or we just wait for the feature to be added 😉

**Comment by alexander-demicev** [comment]
@richardcase should we have a controller temporarily like this one https://github.com/rancher-sandbox/rancher-turtles/pull/178/ to require less setup from users?

**Review by salasberryfin — DISMISSED** [review]

**Review by salasberryfin — DISMISSED** [review]

**Review by alexander-demicev — DISMISSED** [review]

**Review by salasberryfin — APPROVED** [review]

**Review by salasberryfin — APPROVED** [review]

**Pull request merged**
