### PR TITLE
✨ Add azure e2e test job

### LINKED ISSUE #118: [e2e] Add test to cover Azure
### What would you like to be added (User Story)?

As a developer
I would like to have a e2e that uses CAPZ
So that i have confidence that it works with Rancher Turtles

### Detailed Description

Add a e2e test that uses:

- Azure infra provider
- Kubeadm bootstrap/control plave provider
- Use the Rancher generated kubeconfig to connect to created cluster

### Anything else you would like to add?

_No response_

### Label(s) to be applied

kind/feature

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
kind/feature

**What this PR does / why we need it**:
Implement e2e job for testing import functionality for Azure cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #118 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by salasberryfin** [comment]
LGTM peding rebase to fix conflicts.

**Comment by richardcase** [comment]
Lets hold off merging this until the changes for the AWS test have merged as i think it will make it a bit easier.

**Comment by Danil-Grigorev** [comment]
image
Cluster was provisioned successfully and the rancher agent is deployed.

**Review by alexander-demicev — APPROVED** [review]
Thanks!

**Pull request merged**
